// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "Calculator.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



CalculatorApp::Calculator_ptr CalculatorApp::Calculator_Helper::_nil() {
  return ::CalculatorApp::Calculator::_nil();
}

::CORBA::Boolean CalculatorApp::Calculator_Helper::is_nil(::CalculatorApp::Calculator_ptr p) {
  return ::CORBA::is_nil(p);

}

void CalculatorApp::Calculator_Helper::release(::CalculatorApp::Calculator_ptr p) {
  ::CORBA::release(p);
}

void CalculatorApp::Calculator_Helper::marshalObjRef(::CalculatorApp::Calculator_ptr obj, cdrStream& s) {
  ::CalculatorApp::Calculator::_marshalObjRef(obj, s);
}

CalculatorApp::Calculator_ptr CalculatorApp::Calculator_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CalculatorApp::Calculator::_unmarshalObjRef(s);
}

void CalculatorApp::Calculator_Helper::duplicate(::CalculatorApp::Calculator_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

CalculatorApp::Calculator_ptr
CalculatorApp::Calculator::_duplicate(::CalculatorApp::Calculator_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

CalculatorApp::Calculator_ptr
CalculatorApp::Calculator::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CalculatorApp::Calculator_ptr
CalculatorApp::Calculator::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CalculatorApp::Calculator_ptr
CalculatorApp::Calculator::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculator _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculator* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculator;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CalculatorApp::Calculator::_PD_repoId = "IDL:CalculatorApp/Calculator:1.0";


CalculatorApp::_objref_Calculator::~_objref_Calculator() {
  
}


CalculatorApp::_objref_Calculator::_objref_Calculator(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CalculatorApp::Calculator::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
CalculatorApp::_objref_Calculator::_ptrToObjRef(const char* id)
{
  if (id == ::CalculatorApp::Calculator::_PD_repoId)
    return (::CalculatorApp::Calculator_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::CalculatorApp::Calculator::_PD_repoId))
    return (::CalculatorApp::Calculator_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for CalculatorApp::Calculator::add

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble_i_cdouble
class _0RL_cd_9588c41c33939002_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_9588c41c33939002_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double result;
};

void _0RL_cd_9588c41c33939002_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_9588c41c33939002_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_9588c41c33939002_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_9588c41c33939002_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_9588c41c33939002_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_9588c41c33939002_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9588c41c33939002_00000000* tcd = (_0RL_cd_9588c41c33939002_00000000*)cd;
  CalculatorApp::_impl_Calculator* impl = (CalculatorApp::_impl_Calculator*) svnt->_ptrToInterface(CalculatorApp::Calculator::_PD_repoId);
  tcd->result = impl->add(tcd->arg_0, tcd->arg_1);


}

::CORBA::Double CalculatorApp::_objref_Calculator::add(::CORBA::Double n1, ::CORBA::Double n2)
{
  _0RL_cd_9588c41c33939002_00000000 _call_desc(_0RL_lcfn_9588c41c33939002_10000000, "add", 4);
  _call_desc.arg_0 = n1;
  _call_desc.arg_1 = n2;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for CalculatorApp::Calculator::subtract

// Local call call-back function.
static void
_0RL_lcfn_9588c41c33939002_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_9588c41c33939002_00000000* tcd = (_0RL_cd_9588c41c33939002_00000000*)cd;
  CalculatorApp::_impl_Calculator* impl = (CalculatorApp::_impl_Calculator*) svnt->_ptrToInterface(CalculatorApp::Calculator::_PD_repoId);
  tcd->result = impl->subtract(tcd->arg_0, tcd->arg_1);


}

::CORBA::Double CalculatorApp::_objref_Calculator::subtract(::CORBA::Double n1, ::CORBA::Double n2)
{
  _0RL_cd_9588c41c33939002_00000000 _call_desc(_0RL_lcfn_9588c41c33939002_20000000, "subtract", 9);
  _call_desc.arg_0 = n1;
  _call_desc.arg_1 = n2;

  _invoke(_call_desc);
  return _call_desc.result;


}

CalculatorApp::_pof_Calculator::~_pof_Calculator() {}


omniObjRef*
CalculatorApp::_pof_Calculator::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::CalculatorApp::_objref_Calculator(ior, id);
}


::CORBA::Boolean
CalculatorApp::_pof_Calculator::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::CalculatorApp::Calculator::_PD_repoId))
    return 1;
  
  return 0;
}

const CalculatorApp::_pof_Calculator _the_pof_CalculatorApp_mCalculator;

CalculatorApp::_impl_Calculator::~_impl_Calculator() {}


::CORBA::Boolean
CalculatorApp::_impl_Calculator::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "add")) {

    _0RL_cd_9588c41c33939002_00000000 _call_desc(_0RL_lcfn_9588c41c33939002_10000000, "add", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "subtract")) {

    _0RL_cd_9588c41c33939002_00000000 _call_desc(_0RL_lcfn_9588c41c33939002_20000000, "subtract", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
CalculatorApp::_impl_Calculator::_ptrToInterface(const char* id)
{
  if (id == ::CalculatorApp::Calculator::_PD_repoId)
    return (::CalculatorApp::_impl_Calculator*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::CalculatorApp::Calculator::_PD_repoId))
    return (::CalculatorApp::_impl_Calculator*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
CalculatorApp::_impl_Calculator::_mostDerivedRepoId()
{
  return ::CalculatorApp::Calculator::_PD_repoId;
}

POA_CalculatorApp::Calculator::~Calculator() {}

