// This file is generated by omniidl (C++ backend)- omniORB_4_3. Do not edit.
#ifndef __Calculator_hh__
#define __Calculator_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CalculatorApp

_CORBA_MODULE_BEG

#ifndef __CalculatorApp_mCalculator__
#define __CalculatorApp_mCalculator__
  class Calculator;
  class _objref_Calculator;
  class _impl_Calculator;
  
  typedef _objref_Calculator* Calculator_ptr;
  typedef Calculator_ptr CalculatorRef;

  class Calculator_Helper {
  public:
    typedef Calculator_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Calculator, Calculator_Helper> Calculator_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Calculator,Calculator_Helper > Calculator_out;

#endif

  // interface Calculator
  class Calculator {
  public:
    // Declarations for this interface type.
    typedef Calculator_ptr _ptr_type;
    typedef Calculator_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Calculator :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ::CORBA::Double add(::CORBA::Double n1, ::CORBA::Double n2);
    ::CORBA::Double subtract(::CORBA::Double n1, ::CORBA::Double n2);

    // Constructors
    inline _objref_Calculator()  { _PR_setobj(0); }  // nil
    _objref_Calculator(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Calculator();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Calculator(const _objref_Calculator&);
    _objref_Calculator& operator = (const _objref_Calculator&);
    // not implemented

    friend class Calculator;
  };

  class _pof_Calculator : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Calculator() : _OMNI_NS(proxyObjectFactory)(Calculator::_PD_repoId) {}
    virtual ~_pof_Calculator();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Calculator :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Calculator();

    virtual ::CORBA::Double add(::CORBA::Double n1, ::CORBA::Double n2) = 0;
    virtual ::CORBA::Double subtract(::CORBA::Double n1, ::CORBA::Double n2) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CalculatorApp
_CORBA_MODULE_BEG

  class Calculator :
    public virtual CalculatorApp::_impl_Calculator,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Calculator();

    inline ::CalculatorApp::Calculator_ptr _this() {
      return (::CalculatorApp::Calculator_ptr) _do_this(::CalculatorApp::Calculator::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CalculatorApp
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CalculatorApp::Calculator::_marshalObjRef(::CalculatorApp::Calculator_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Calculator
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Calculator
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculator
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Calculator
#endif

#endif  // __Calculator_hh__

